STYLE: Replace VTK_OVERRIDE with override
This commit is required to support with VTK >= 8.90. It fixes
error like the following:

  /tmp/UKFTractography/InteractiveUKF/Logic/vtkSlicerInteractiveUKFLogic.h:52:47: error: expected ‘;’ at end of member declaration
     void PrintSelf(ostream& os, vtkIndent indent) VTK_OVERRIDE;
                                                 ^